name: Test

on: [ push ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        crystal: [1.0.0, latest, nightly]
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install shards
        run: shards install
      - name: Run tests
        run: crystal spec --order=random --error-on-warnings --error-trace -v